sudo: required

services:
  - docker

before_install:
  - docker build -t ayoubbelghar/docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true ayoubbelghar/docker-react-travis npm run test -- --coverage